# -*- coding: utf-8 -*-
"""191_ContactTracing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jn8NECH7zABnoSbrbyuA5SUlCKM7vYFY

## 191 Final Project: Contact Tracing
*Proponents: Bernido, Jacinto, Rivas, Sijera*

Identifying potentially infected people given the name of an infected person that made contact with them. This code was written in Google Colab.
"""

!pip install pygal
import pandas as pd
import pygal
import numpy as np
from sklearn.cluster import DBSCAN

from IPython.display import display, HTML
base_html = """
<!DOCTYPE html>
<html>
  <head>
  <script type="text/javascript" src="http://kozea.github.com/pygal.js/javascripts/svg.jquery.js"></script>
  <script type="text/javascript" src="https://kozea.github.io/pygal.js/2.0.x/pygal-tooltips.min.js""></script>
  </head>
  <body>
    <figure>
      {rendered_chart}
    </figure>
  </body>
</html>
"""

from google.colab import drive
drive.mount('/content/gdrive')

path = '/content/gdrive/Shareddrives/191_ContactTracing/ContactTracing_MOCKDATA.json'
dataFrame = pd.read_json(path)
dataFrame.head()

"""## Plot of 11,000 locations of 1000 people in a 0.1x0.1 km grid in a 1 hour timeframe"""

disp_dict = {}
for index, row in dataFrame.iterrows():
    if row['User'] not in disp_dict.keys():
        disp_dict[row['User']] = [(row['Latitude'], row['Longitude'])]
    else:
        disp_dict[row['User']].append((row['Latitude'], row['Longitude']))
xy_chart = pygal.XY(stroke=False)
[xy_chart.add(k,v) for k,v in sorted(disp_dict.items())]
display(HTML(base_html.format(rendered_chart=xy_chart.render(is_unicode=True))))

"""## Application of DBScan with parameters: eps = 0.0018288 (6ft) and min_samples = 2 people"""

safe_distance = 0.0018288 # a radial distance of 6 feet in kilometers
model = DBSCAN(eps=safe_distance, min_samples=2, metric='haversine').fit(dataFrame[['Latitude', 'Longitude']])
core_samples_mask = np.zeros_like(model.labels_, dtype=bool)
core_samples_mask[model.core_sample_indices_] = True
labels = model.labels_
dataFrame['Cluster'] = model.labels_.tolist()

"""## Clusters of people within 6ft of each other specified in shades of red"""

disp_dict_clust = {}
for index, row in dataFrame.iterrows():
    if row['Cluster'] not in disp_dict_clust.keys():
        disp_dict_clust[row['Cluster']] = [(row['Latitude'], row['Longitude'])]
    else:
        disp_dict_clust[row['Cluster']].append((row['Latitude'], row['Longitude']))
print(len(disp_dict_clust.keys()))
from pygal.style import LightenStyle
dark_lighten_style = LightenStyle('#F35548')
xy_chart = pygal.XY(stroke=False, style=dark_lighten_style)
[xy_chart.add(str(k),v) for k,v in disp_dict_clust.items()]
display(HTML(base_html.format(rendered_chart=xy_chart.render(is_unicode=True))))

"""## Checking Potential Infected Persons

Users may assign the name of an infected person to the variable inputName to check who they came in contact with in a particular area and timeframe. Values is defaultly set to "Abdel Terne", but it may be changed to any of the 1000 people of the population, listed in the 1000people.csv file.
"""

inputName = "Abdel Terne"
inputNameClusters = set()
for i in range(len(dataFrame)):
    if dataFrame['User'][i] == inputName:
        inputNameClusters.add(dataFrame['Cluster'][i])

infected = set()
for cluster in inputNameClusters:
    if cluster != -1:
        namesInCluster = dataFrame.loc[dataFrame['Cluster'] == cluster, 'User']
        for i in range(len(namesInCluster)):
            name = namesInCluster.iloc[i]
            if name != inputName:
                infected.add(name)

"""Potentially infected persons are displayed, and may be contacted for Covid Testing



"""

print("Potential infections are:",*infected,sep="\n" )